### ISSUE TITLE
爬取链家的spider 启动失败

### ISSUE THREAD

**Issue by solo-code** [kezhenxu94/house-renting#19]
下面是启动 时的log:

2018-06-01 06:13:15 [scrapy.core.engine] INFO: Spider opened
2018-06-01 06:13:15 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-06-01 06:13:15 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/house-renting/crawler/house_renting/base_spider.py", line 12, in start_requests
    city_url = city_url_mappings[city]
KeyError: '北'
2018-06-01 06:13:15 [scrapy.core.engine] INFO: Closing spider (finished)
2018-06-01 06:13:15 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 6, 1, 6, 13, 15, 873859),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'memusage/max': 57556992,
 'memusage/startup': 57556992,
 'start_time': datetime.datetime(2018, 6, 1, 6, 13, 15, 859019)}
2018-06-01 06:13:15 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by solo-code** [comment]
Docker version 18.03.1-ce, build 9ee9f40

**Comment by kezhenxu94** [comment]
@solo-code 你的城市名字只有一个北字？

**Comment by kezhenxu94** [comment]
@solo-code 这可能是设置城市有点问题，参考#18 把 (u'北京') 写成 (u'北京',) 括号里加多一个逗号

**Comment by kezhenxu94** [comment]
长时间没有反馈，将关闭 issue
