### ISSUE TITLE
启动docker失败

### ISSUE THREAD

**Issue by alexliangshi** [kezhenxu94/house-renting#21]
root@dockerU:/home/house-renting# docker -v
Docker version 1.13.1, build 092cba3

root@dockerU:/home/house-renting# docker-compose up --build -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.2', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2457, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2171, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 22, in <module>
    from ..project import NoSuchService
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 18, in <module>
    from .service import ContainerNet
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 13, in <module>
    from docker.utils import LogConfig
ImportError: cannot import name LogConfig

**Comment by kezhenxu94** [comment]
尝试运行一下: `pip install --upgrade docker-py`

更多是关于 docker 的问题，这里看到跟你一模一样的 issue:

https://github.com/docker/compose/issues/1567

**Comment by kezhenxu94** [comment]
长时间没有反馈，将关闭 Issue
